# Generated by Django 4.1.6 on 2023-02-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_room_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interested_users',
            name='room_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
        migrations.AlterField(
            model_name='interested_users',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='interested_users',
            constraint=models.UniqueConstraint(fields=('user_id', 'room_id'), name='interested_user'),
        ),
    ]
