# Generated by Django 4.1.6 on 2023-02-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_room_image1_alter_room_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='space',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
    ]
