# Generated by Django 4.1.6 on 2023-02-02 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_room_space'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_subject', models.CharField(max_length=255)),
                ('email_sender', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_receiver', models.EmailField(blank=True, max_length=255, null=True)),
                ('email_body', models.TextField(blank=True, null=True)),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
    ]
