# Generated by Django 4.1.6 on 2023-02-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_kyc_user_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc_user',
            name='document',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
